Hw04
AleksandrDanilevskii/python-basic-homeworks pull request #4
Opened 2022-11-19 10:45 UTC by AleksandrDanilevskii

Привет!

По этому ДЗ мне неясен остался один момент:
нужно ли было оборачивать _sessionmaker_ в _scoped_session_ при асинхронной работе? Судя по коду тестов, мне показалось, что да. Но в таком случае возникало предупреждение о том, что такое использование _deprecated_. Поэтому я от _scoped_session_ отказался. Как правильно?

2022-11-27 11:57 UTC, mahenzon commented
> нужно ли было оборачивать _sessionmaker_ в _scoped_session_ при асинхронной работе

отличный вопрос! в этой домашке не нужно. Но если в дальнейшем понадобится, нужно делать это по-другому: https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#using-asyncio-scoped-session

Суть в том, что для scoped session в асинк использовании нужно вытаскивать текущую задачу (в доке пример есть)

2022-11-27 11:58 UTC, mahenzon commented on homework_04/jsonplaceholder_requests.py
> +        return [{field: user[field] for field in fields} for user in data]
а в чём тут отличие от того, что будет, если вернуть просто исходный список? только отсечение лишних полей?

2022-11-27 12:00 UTC, mahenzon commented on requirements.txt
> +SQLAlchemy==1.4.44
необходимо ещё добавить `asyncpg`:

```
SKIPPED [1] testing/test_homework_04/test_main.py:4: could not import 'homework_04': No module named 'asyncpg'
```

2022-11-27 12:00 UTC, mahenzon requested changes
Отличная работа
Нужно только в одном месте поправить (добавить зависимость)

2022-11-27 13:57 UTC, AleksandrDanilevskii commented on homework_04/jsonplaceholder_requests.py
> +        return [{field: user[field] for field in fields} for user in data]
Да, я хотел иметь возможность передать в функцию список с полями, которые нужно вернуть, а остальные отсекать

2022-11-27 14:29 UTC, AleksandrDanilevskii commented on requirements.txt
> +SQLAlchemy==1.4.44
Добавил в зависимости asyncpg==0.27.0.

2022-12-05 17:22 UTC, mahenzon commented on homework_04/jsonplaceholder_requests.py
> +        return [{field: user[field] for field in fields} for user in data]
обычно в апи не меняются поля (принято не нарушать совместимость), так что тут это не очень актуально. но в целом норм идея

2022-12-05 17:22 UTC, mahenzon approved these changes
Отличная работа

2022-12-05 17:33 UTC, merged